apiVersion: v1
kind: Pod
metadata:
  name: debug-pod-inside
  namespace: redis
  labels:
    app: debug
spec:
  containers:
    - name: debug-container
      image: nicolaka/netshoot
      command: ["/bin/bash", "-c", "sleep 3600"]