apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: monitoring  # Namespace where Prometheus is running
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-cluster
  namespaceSelector:
    matchNames:
      - redis
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
