{{- if .Values.global.injectPDPRedisCredentials }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-redis-cluster
  namespace: redis
spec:
  provider: {{ .Values.global.secretProvider }}
  secretObjects:
    - secretName: redis-cluster
      type: Opaque
      data:
        - objectName: redis-password
          key: redis-password
  parameters:
    {{- if eq .Values.global.secretProvider "aws" }}
    objects: |
      - objectName: {{ .Values.global.secrets.redisPasswordKVRef | quote }}
        objectType: secretsmanager
        objectAlias: redis-password
        objectVersion: {{ .Values.global.secrets.redisPassword | quote }}
    {{- else if eq .Values.global.secretProvider "azure" }}
    keyvaultName: {{ .Values.global.keyVaultName }}
    tenantId: {{ .Values.global.azureTenantID }}
    usePodIdentity: "false"
    objects: |
      array:
        - |
          objectName: {{ .Values.global.secrets.redisPasswordKVRef | quote }}
          objectType: secret
          objectAlias: redis-password
          objectVersion: {{ .Values.global.secrets.redisPassword | quote }}
    {{- else if eq .Values.global.secretProvider "gcp" }}
    secrets: |
      - resourceName: {{ .Values.global.secrets.redisPasswordKVRef | quote }}
        path: "redis-password"
    {{- else if eq .Values.global.secretProvider "vault" }}
    vaultAddress: {{ .Values.global.hcVaultAddress }}
    roleName: "redis-cluster"
    objects: |
      - objectName: redis-password 
        secretKey: redis-password 
        secretPath: {{ .Values.global.secrets.redisPasswordKVRef | quote }}
    {{- end }}
{{- end }}
