apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-redis-cluster
  namespace: redis
spec:
  provider: {{ .Values.global.secretProvider }}
  secretObjects:
    - secretName: redis-cluster
      type: Opaque
      data:
        - objectName: redis-password
          key: redis-password
  parameters:
    {{- if eq .Values.global.secretProvider "aws" }}
    objects: |
      - objectName: "PDP_REDIS_PASSWORD"
        objectType: "secretsmanager"
        objectAlias: "redis-password"
    {{- else if eq .Values.global.secretProvider "azure" }}
    keyvaultName: {{ .Values.global.keyVaultName }}
    tenantId: {{ .Values.global.azureTenantID }}
    usePodIdentity: "false"
    objects: |
      array:
        - |
          objectName: "PDP_REDIS_PASSWORD"
          objectType: "secret"
          objectAlias: "redis-password"
    {{- else if eq .Values.global.secretProvider "gcp" }}
    secrets:
      - resourceName: "projects/{{ .Values.global.gcpProjectID }}/secrets/PDP_REDIS_PASSWORD/versions/latest"
        path: "redis-password"
    {{- else if eq .Values.global.secretProvider "vault" }}
    vaultAddress: {{ .Values.global.hcVaultAddress }}
    roleName: "redis-cluster"
    objects: |
      - objectName: "redis-password"
        secretPath: "secret/data/redis-cluster"
        secretKey: "PDP_REDIS_PASSWORD"
    {{- end }}
{{- end }}